name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Checkout FATE Repo
        uses: actions/checkout@v4
        with:
          repository: 'FederatedAI/FATE'
          ref: 'v1.11.4'
          path: 'FATE'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build Package
        run: |
          yes | Platform=arm64 FATE_DIR=../FATE Build_Basic=1 Build_NN=0 \
          Build_FUM=0 Build_Spark=0 Build_OP=0 Build_IPCL=0 Build_GPU=0 \
          Build_LLM=0 Build_LLM_VERSION=v1.2.0 \
          IPCL_PKG_DIR=/root/pailliercryptolib_python/ IPCL_VERSION=v1.1.3 \
          bash docker-build/build.sh package
      - name: Build Base
        run: |
          Platform=arm64 FATE_DIR=../FATE Build_Basic=1 Build_NN=0 \
          Build_FUM=0 Build_Spark=0 Build_OP=0 Build_IPCL=0 Build_GPU=0 \
          Build_LLM=0 Build_LLM_VERSION=v1.2.0 \
          IPCL_PKG_DIR=/root/pailliercryptolib_python/ IPCL_VERSION=v1.1.3 \
          bash docker-build/build.sh base
      - name: Build Modules
        continue-on-error: true
        run: |
          Platform=arm64 FATE_DIR=../FATE Build_Basic=1 Build_NN=0 \
          Build_FUM=0 Build_Spark=0 Build_OP=0 Build_IPCL=0 Build_GPU=0 \
          Build_LLM=0 Build_LLM_VERSION=v1.2.0 \
          IPCL_PKG_DIR=/root/pailliercryptolib_python/ IPCL_VERSION=v1.1.3 \
          bash docker-build/build.sh modules
      - name: Verify Images
        run: |
          docker images
