name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Clone FATE repo
        uses: actions/checkout@v4
        with:
          repository: 'FederatedAI/FATE'
          ref: 'v1.11.4'
          path: '../'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: build
        run: |
          docker buildx ls